Asp mods
c2pa-org/ccpa-org.github.io pull request #6
Opened 2021-02-20 23:37 UTC by andyparsons

learning a little Hugo and minor changes made

2021-02-20 23:40 UTC, lrosenthol requested changes

2021-02-20 23:40 UTC, lrosenthol commented on content/en/_index.md
> +
Was actually leaving those in as I am going to put the logos in tomorrow!

2021-02-20 23:40 UTC, lrosenthol commented on config.toml
> +  github = "https://github.com/c2pa-org"
Thanks!

2021-02-21 15:24 UTC, andyparsons commented on content/en/_index.md
> +
👍

2021-02-21 15:43 UTC, andyparsons commented on config.toml
> +  github = "https://github.com/c2pa-org"
reverting the other change and merging just this.

2021-02-21 15:44 UTC, merged